@startuml

title: Un usuario se loguea con password inválido

":TestCase" -> ":AlgoMail": verificacionInicial("joaquin", "password invalido")
create "mf :AutenticacionMultiple"
":AlgoMail" -> "mf :AutenticacionMultiple" : new(usuarios)
":AlgoMail" -> "mf :AutenticacionMultiple" : verificacionInicial(nombreUsuario, pwdLogueo)
return [fallo : MultiFactorFallido]
":AlgoMail" --> ":TestCase": [fallo : MultiFactorFallido]

":TestCase" -> "fallo : MultiFactorFallido": verificacionSecundaria(codigoInvalido)
create ValidacionInapropiada
"fallo : MultiFactorFallido" -> ValidacionInapropiada: throw
@enduml